### ISSUE TITLE
Spurious blank lines in output from -d option

### ISSUE THREAD

**Issue by tomblackie-xmos** [xmos/host_xvf_control#102]
When xvf_host -d is run, the terminal output has spurious blank lines after GPI_EVENTT_CONFIG and all the AUDIO_MGR_OP_xxx reports

**Comment by uvvpavel** [comment]
@mbanth The fix for this issue is quite straightforward, but it will come from fwk_xvf. I don't remember why I've put 4 days, but I remember thinking that it should take some time for the CI and PRs in 3 repos. Now that I think about it, it can take 2 - 3 depending on if I get PR reviews fast.

**Comment by mbanth** [comment]
> @mbanth The fix for this issue is quite straightforward, but it will come from fwk_xvf. I don't remember why I've put 4 days, but I remember thinking that it should take some time for the CI and PRs in 3 repos. Now that I think about it, it can take 2 - 3 depending on if I get PR reviews fast.

Thanks for this information, @uvvpavel.  I have lowered the SP value to 3.

**Comment by uvvpavel** [comment]
fixed in https://github.com/xmos/fwk_xvf/pull/104
