### ISSUE TITLE
Libcommand_map

### ISSUE THREAD

**Issue by szbeni** [xmos/host_xvf_control#118]
Hi,
Where can I find the source code of libcommand_map.so?
Only can find the precompiled version in the xvf3800 binary files.
Thanks,
Beni

**Comment by mbanth** [comment]
Hi szbeni,

Thank you for submitting this question.  The library is created as part of the XVF3800 build process.  If you obtain[ the XVF3800 source code](https://www.xmos.com/develop/xvf3800/#software) and follow the build process documented in the User Guide, you should find that a copy of the library has been created.

The information and procedures used to build the library for use with XVF3800 are contained in various files and they involve numerous transformations.  No simple set of source files for the production library exists.

The source code of this repository does include a dummy command map which you will find in the `tests` directory.  This file includes the API used by the host application to when interfacing with lib_command_map.so.

Regards,
mbanth
